version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/frontend-app

hooks:

  BeforeInstall:
    - location: scripts/stop_nginx.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

    - location: scripts/build_app.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/deploy_nginx.sh
      timeout: 300
      runas: ubuntu